# Generated by Django 4.0 on 2021-12-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTagMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_tag_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageTagMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_tag_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LevelTagMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_tag_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='images/no_image.png', upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('producer', models.CharField(default='', max_length=50)),
                ('contents', models.TextField(blank=True, default='', max_length=1000)),
                ('language_tags', models.TextField(blank=True, default='', max_length=500)),
                ('level_tags', models.TextField(blank=True, default='', max_length=500)),
                ('content_tags', models.TextField(blank=True, default='', max_length=500)),
                ('urls', models.URLField(blank=True, default='')),
                ('price', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=500)),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default='3', verbose_name='レビュースコア')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='product.product')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.user', verbose_name='投稿ユーザ')),
            ],
        ),
    ]
