# Generated by Django 4.0 on 2021-12-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='images/no_image.png', upload_to='images'),
        ),
    ]
