# Generated by Django 4.0 on 2022-01-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='urls',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
