# Generated by Django 4.0 on 2022-01-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='urls',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
