# Generated by Django 4.0 on 2022-01-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ad_image',
            field=models.TextField(blank=True, default='', max_length=1500),
        ),
    ]
